
```{r}
library(tidyverse)
library(BiocManager)
library(GEOquery)
library(affy)
library(limma)
library(CONOR)
library(janitor)
library(patchwork)
options(scipen = 999)
```


```{r}
gse <- "GSE18732"


## Extraction of PROCESSED expressionSet ----
Gallagher_proc <- getGEO(GEO = paste0(gse))
Gallagher_proc <- Gallagher_proc[[paste0(gse,"_series_matrix.txt.gz")]]

## QC ##
expr <- exprs(Gallagher_proc)
expr <- backgroundCorrect(expr, method= "normexp") # background correct
expr <- normalizeBetweenArrays(object = expr) # normalize expression profiles
expr <- log2(expr)
expr <- expr %>% as.data.frame %>% rownames_to_column(var = 'ID') 


# Boxplots
expr %>%
  gather(gsm, value, -ID) %>% 
  ggplot(aes(x = gsm, y = value))+
  geom_boxplot()
# Histogram
expr %>%
  gather(gsm, value, -ID) %>% 
  ggplot(aes(x =value))+
  geom_histogram()


## Annotate data expressionSet
anno <-
  as.data.frame(Gallagher_proc@featureData@data) %>%
    # rownames_to_column("ID") %>% 
    left_join(anno_db, by = "ID")
  
anno_expr <- dplyr::full_join(anno,expr, by = 'ID') # merge expr and anno
   
## EXTRACT/CLEAN PHENO DATA ##

column_names <- 
  pData(Gallagher_proc) %>% 
  dplyr::select(contains("characteristics")) %>% 
    mutate_all(.funs = function(x) {word(x, 1, sep = " ") %>% str_remove(":")}) %>% 
    distinct() %>% 
    t() %>% 
    as.data.frame %>% 
    rownames_to_column("row") %>% 
    dplyr::select(-row) %>% 
    mutate(V1 = as.character(V1)) %>% 
    pull(V1) %>% 
    prepend("geo_accession") %>% 
    prepend("title") %>% 
    prepend("group")

pheno_eset <-
  pData(Gallagher_proc) %>% 
  dplyr::select(title, contains("characteristics")) %>% 
  rownames_to_column("geo_accession") %>% 
  mutate(group = str_extract(title, "normal|glucoseIntolerant|diabetic")) %>% 
  mutate(group = recode(group, "glucoseIntolerant" = "IR", "normal" = "CON", "diabetic" = "T2D"),
         geo_accession = paste0(geo_accession,".CEL")) %>% 
  dplyr::select(geo_accession, title, group, everything()) %>% 
  setNames(column_names) %>% 
  mutate_at(.vars = vars(t2dmknown:trunk_limb_fm_ratio), .funs = function(x) {word(x, 2, sep = " ") %>% str_remove(":")})


## Set-up comparisons
groups <- pheno_eset %>% distinct(group) %>% pull

my_comparisons <- 
  list(
    c("CON", "IR"),
    c("CON", "T2D")
  )


## Plot data


plot_data <-
  anno_expr %>% 
  filter(str_detect(Description, ".*Myostatin.*")) %>% 
  dplyr::select(GSM465274:GSM465391) %>% 
  t() %>% 
  as.data.frame %>% 
  rownames_to_column("geo_accession") %>% 
  dplyr::rename(MSTN = V1) %>% 
  left_join(
    pheno_eset %>% 
      mutate(group = str_remove(group, ".CEL")) %>% 
      dplyr::rename(geo_accession = group, group = geo_accession) %>% 
      mutate_at(.vars = vars(t2dmknown:trunk_limb_fm_ratio), as.numeric),
    by = "geo_accession"
    )
  

anno_proc <-
  Gallagher_proc@featureData@data %>% 
    dplyr::select(ID, Description) %>% 
    filter(str_detect(Description, ".*Myostatin.*")) %>% 
    mutate(SYMBOL = "MSTN") %>% 
    dplyr::select(ID, SYMBOL) %>% 
    left_join(expr_proc, by = "ID")
  
  

```

```{r}
#CORRELATION DATA
library(Hmisc)

corVars <- plot_data %>% keep(is.numeric) %>% names

plot_data.cor <- plot_data %>% dplyr::select(corVars)
plot_data.cor.con <- plot_data %>% filter(group == "CON") %>% dplyr::select(corVars)
plot_data.cor.ir <- plot_data %>% filter(group == "IR") %>% dplyr::select(corVars)
plot_data.cor.t2d <- plot_data %>% filter(group == "T2D") %>% dplyr::select(corVars)

res <- rcorr(as.matrix(plot_data.cor), type="spearman")
res.con <- rcorr(as.matrix(plot_data.cor.con), type="spearman")
res.ir <- rcorr(as.matrix(plot_data.cor.ir), type="spearman")
res.t2d <- rcorr(as.matrix(plot_data.cor.t2d), type="spearman")

# ++++++++++++++++++++++++++++
# flattenCorrMatrix
# ++++++++++++++++++++++++++++
# cormat : matrix of the correlation coefficients
# pmat : matrix of the correlation p-values
flattenCorrMatrix <- function(cormat, pmat) {
  ut <- upper.tri(cormat)
  data.frame(
    row = rownames(cormat)[row(cormat)[ut]],
    column = rownames(cormat)[col(cormat)[ut]],
    cor  =(cormat)[ut],
    p = pmat[ut]
    )
}

corsig = flattenCorrMatrix(res$r, res$P)
corsig.con = flattenCorrMatrix(res.con$r, res.con$P)
corsig.ir = flattenCorrMatrix(res.ir$r, res.ir$P)
corsig.t2d = flattenCorrMatrix(res.t2d$r, res.t2d$P)

## VIEW MATRIX ##
# corsig %>% 
#   filter(cor < 1 & cor > -1) %>%
#   filter((row == "MSTN" | column == "MSTN")) %>%
#   arrange(-abs(cor)) 
# 
## Create an overall correlation table with all 4 comparisons
list_names <- c("corsig", "corsig.con", "corsig.ir", "corsig.t2d")
corsig_list <- list(corsig, corsig.con, corsig.ir, corsig.t2d)

corr_table_paper <- 
  lapply(corsig_list, function(x){
    x %>% 
      filter(cor < 1 & cor > -1) %>%
      filter((row == "MSTN" | column == "MSTN")) %>%
      arrange(-abs(cor)) 
  }) %>%
    setNames(list_names) %>% 
    bind_rows(.id = "table") %>% 
    # filter(p < 0.05) %>% 
    mutate(cor = ifelse(p < 0.05, paste0(round(cor,2),"*"), round(cor,2))) %>% 
    dplyr::select(-row, -p) %>% 
    filter(!str_detect(column, "^log_.")) %>% 
    pivot_wider(names_from = "table", values_from = c("cor")) %>% 
    arrange(column)

## Write to file
# write_csv(corr_table_paper, "product_files/Gallagher_MSTN_correlation_table.csv")

```


```{r fig.height=5.5, fig.width=16.5}


Fig2H <- 
  final_plot_data %>%
    ggplot(aes(x = reorder(comparison, logFC), y = logFC))+
    geom_col(aes(fill = comparison), color = "black")+
    scale_y_continuous(limits = c(-1,1))+
    scale_fill_manual(name = "", values = c("white", "black"))+
    geom_text(aes(label = paste0("p=",round(adj.P.Val,2)),
                 vjust = ifelse(logFC >= 0, -0.5, 1.5)),
              size = 3)+
    geom_hline(aes(yintercept = 0))+
    theme_classic()+
    labs(y=expression(paste(italic("MSTN "), log[2], " fold-change"))) + 
    theme(
      axis.text.x = element_blank(),
      axis.title.x = element_blank(),
      axis.ticks.x = element_blank(),
      axis.line.x = element_blank(),
      strip.background = element_blank(),
      panel.grid.major.y = element_line(color = "grey80"),
      panel.grid.minor.y = element_line(color = "grey90"),
      panel.spacing = unit(0, "lines")
    )+
    facet_grid(~id)

Fig2I <- 
  plot_data %>% 
    filter(hba1c > 0 & MSTN > 6) %>% 
    ggplot(aes(x = hba1c, y = MSTN))+
    geom_smooth(method = lm, color = "black")+
    geom_point(size = 3)+
    theme_classic()+
    scale_x_continuous(breaks = scales::pretty_breaks())+
    scale_y_continuous(breaks = scales::pretty_breaks())+
    ggpubr::stat_cor(method = "spearman")+
    theme(
        text = element_text(size = 18, face = "bold"),
        axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)),
        axis.title.x = element_text(margin = margin(t = 20, r = 0, b = 0, l = 20)),
        axis.text.y = element_text(colour="black"),
        axis.text.x = element_text(colour="black"),
        legend.position = "none",
        strip.background = element_blank()
        ) +
     labs(y=expression(paste(italic("MSTN "), log[2], " mRNA expression")),
         x = "HbA1c (%)")

cowplot::plot_grid(
  Fig2H, Fig2I,
  labels = c("h", "i"), 
  label_size = 24, 
  ncol = 2, 
  align = "hv", 
  axis = "bt"
  )


```

```{r fig.height=5, fig.width=15}
plot_data %>% 
    filter(hba1c > 0 & MSTN > 6) %>% 
    ggplot(aes(shape = group, x = hba1c, y = MSTN))+
    geom_smooth(method = lm, color = "black")+
    geom_point(size = 3)+
    theme_classic()+
    scale_x_continuous(breaks = scales::pretty_breaks())+
    scale_y_continuous(breaks = scales::pretty_breaks())+
  scale_shape_manual(values = c(16,15,17))+
    ggpubr::stat_cor(method = "spearman", label.x.npc = .5)+
    theme(
        text = element_text(size = 18, face = "bold"),
        axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)),
        axis.title.x = element_text(margin = margin(t = 20, r = 0, b = 0, l = 20)),
        axis.text.y = element_text(colour="black"),
        axis.text.x = element_text(colour="black"),
        legend.position = "none",
        strip.background = element_blank()
        ) +
  facet_grid(~group, scales = "free")+
     labs(y=expression(paste(italic("MSTN "), log[2], " mRNA expression")),
         x = "HbA1c (%)")
```

